version: '3.9'

services:
  whoami:
    image: traefik/whoami:latest
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.local`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - traefik_overlay
networks:
  traefik_overlay:
    external: true