version: '3'

services:
  traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.network=traefik_overlay"
    ports: 
      - target: 80
        published: 80
        mode: host
      - target: 8080
        published: 8080
    labels:      
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - $PWD/traefik.toml:/etc/traefik/traefik.toml
      # - $PWD/traefik.yml:/etc/traefik/traefik.yml
    networks:
      traefik_overlay:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.07'
          memory: 64M  
networks:
  traefik_overlay:
    external: true
